export const PROPERTY_ORDER: string[] = [
  'content',
  // Positioning
  'z-index',
  'position',
  'top',
  'bottom',
  'left',
  'right',
  'float',
  'clear',
  // Display
  'display',
  'visibility',
  'box-sizing',
  'overflow',
  'overflow-x',
  'overflow-y',
  // Flexbox
  'flex',
  'flex-grow',
  'flex-shrink',
  'flex-basis',
  'flex-direction',
  'flex-wrap',
  'justify-content',
  'justify-items',
  'align-content',
  'align-items',
  'place-items',
  'justify-self',
  'align-self',
  // Grid
  'grid',
  'grid-template',
  'grid-template-rows',
  'grid-template-columns',
  'grid-template-areas',
  'grid-auto-rows',
  'grid-auto-columns',
  'grid-auto-flow',
  'grid-gap',
  'grid-row-gap',
  'grid-column-gap',
  'grid-area',
  'grid-row',
  'grid-row-start',
  'grid-row-end',
  'grid-column',
  'grid-column-start',
  'grid-column-end',
  'gap',
  // Size
  'width',
  'min-width',
  'max-width',
  'height',
  'min-height',
  'max-height',
  // Spacing
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  // Text
  'font',
  'font-size',
  'font-family',
  'font-style',
  'font-variant',
  'font-weight',
  'font-stretch',
  'font-size-adjust',
  'line-height',
  'color',
  'text-align',
  'text-align-last',
  'text-decoration',
  'text-emphasis',
  'text-emphasis-color',
  'text-emphasis-style',
  'text-emphasis-position',
  'text-indent',
  'text-justify',
  'text-outline',
  'text-transform',
  'text-wrap',
  'text-overflow',
  'text-overflow-ellipsis',
  'text-overflow-mode',
  'text-shadow',
  'letter-spacing',
  'word-spacing',
  'word-wrap',
  'word-break',
  'tab-size',
  'hyphens',
  'white-space',
  'vertical-align',
  // Background
  'background',
  'background-color',
  'background-image',
  'background-repeat',
  'background-attachment',
  'background-position',
  'background-position-x',
  'background-position-y',
  'background-clip',
  'background-origin',
  'background-size',
  // Border
  'border',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-width',
  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'border-style',
  'border-top-style',
  'border-right-style',
  'border-bottom-style',
  'border-left-style',
  'border-color',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'border-radius',
  'border-spacing',
  'border-collapse',
  'border-image',
  'border-image-source',
  'border-image-slice',
  'border-image-width',
  'border-image-outset',
  'border-image-repeat',
  // Animation
  'transition',
  'transition-delay',
  'transition-timing-function',
  'transition-duration',
  'transition-property',
  'animation',
  'animation-name',
  'animation-duration',
  'animation-play-state',
  'animation-timing-function',
  'animation-delay',
  'animation-iteration-count',
  'animation-direction',
  // Background
  'background',
  'background-color',
  'background-image',
  'background-repeat',
  'background-attachment',
  'background-position',
  'background-position-x',
  'background-position-y',
  'background-clip',
  'background-origin',
  'background-size',
  // List
  'list-style',
  'list-style-position',
  'list-style-type',
  'list-style-image',
  // Others
  'opacity',
  'transform',
  'clip',
  'clip-path',
  // Quotes
  'quotes',
  // Counters
  'counter-increment',
  'counter-reset',
  // Box Shadow and Object
  'box-shadow',
  'object-fit',
  'object-position',
  // Box Decoration Break and Resize
  'box-decoration-break',
  'resize',
  // Appearance
  'appearance',
  // User Interaction
  'cursor',
  'user-select',
  'pointer-events',
  // Filters
  'filter',
  'backdrop-filter'
];
